name: Deploy OSSI2 to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      env:
        VITE_API_URL: https://ossi2.esedu.fi/api
        VITE_CLIENT_ID: ${{ secrets.PROD_CLIENT_ID }}
        VITE_TENANT_ID: ${{ secrets.PROD_TENANT_ID }}
        VITE_REDIRECT_URI: https://ossi2.esedu.fi/
        VITE_POST_LOGOUT_REDIRECT_URI: https://ossi2.esedu.fi/
      
    - name: Deploy to production server
      uses: appleboy/scp-action@master
      with:
        host: ossi2.esedu.fi
        username: ${{ secrets.PROD_SSH_USERNAME }}
        key: ${{ secrets.PROD_SSH_KEY }}
        source: "dist/*"
        target: "/var/www/ossi2.esedu.fi/html"
        strip_components: 1
        
    - name: Configure Nginx and restart
      uses: appleboy/ssh-action@master
      with:
        host: ossi2.esedu.fi
        username: ${{ secrets.PROD_SSH_USERNAME }}
        key: ${{ secrets.PROD_SSH_KEY }}
        script: |
          sudo systemctl reload nginx